server:
  ssl:
    key-store: classpath:keystore/npstl.p12
    key-alias: npstl
spring:
  datasource:
    url: jdbc:h2:file:./db/npsdb
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: ${H2_ADMIN_PASSWORD_HASH}
        web-allow-others: true
      path: /h2