version: "3.9"
services:
  npsapp:
    build:
      context: .
      dockerfile_inline: |
        FROM tomcat:9
        EXPOSE 8080 8443 9092
        COPY ROOT.war /usr/local/tomcat/webapps/
    image: npsapp
    hostname: nps
    container_name: npsapp
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"
        tag: npsapp
    environment:
      - BX_TOKEN=${BX_TOKEN}
      - PORTAL_URL=${PORTAL_URL}
      - REST_ID=${REST_ID}
      - DB_PASSWORD=${DB_PASSWORD}
      - H2_ADMIN_PASSWORD=${H2_ADMIN_PASSWORD}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - H2_PORT=${H2_PORT}
    volumes:
      - type: bind
        source: ../db
        target: /tmp/db
      - type: bind
        source: ./conf/ca_bundle.crt
        target: /usr/local/tomcat/conf/ca_bundle.crt
      - type: bind
        source: ./conf/certificate.crt
        target: /usr/local/tomcat/conf/certificate.crt
      - type: bind
        source: ./conf/private.key
        target: /usr/local/tomcat/conf/private.key
      - type: bind
        source: ./conf/server.xml
        target: /usr/local/tomcat/conf/server.xml
    ports:
      - ${HTTP_PORT}:8080
      - ${HTTPS_PORT}:8443
      - ${H2_PORT}:9092
