version: "3.9"
services:
  npsapp:
    build: .
    image: npsapp
    hostname: nps
    container_name: npsapp
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"
        tag: npsapp
    environment:
      - BX_TOKEN=${BX_TOKEN}
      - PORTAL_URL=${PORTAL_URL}
      - REST_ID=${REST_ID}
      - DB_PASSWORD=${DB_PASSWORD}
      - H2_ADMIN_PASSWORD=${H2_ADMIN_PASSWORD}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - H2_PORT=${H2_PORT}
    volumes:
      - ./db:/tmp/db
    ports:
      - ${HTTP_PORT}:8080
      - ${HTTPS_PORT}:8443
      - ${H2_PORT}:9092
